name: hold_on_pop
description: A Flutter package that provides a widget that shows a popup when the user presses their finger and closes when they release it, similar to the functionality in Instagram.
version: 0.0.2
homepage: https://minis.codes
repository: https://github.com/sytungan/hold_on_pop
issue_tracker: https://github.com/sytungan/hold_on_pop/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
